<?php

/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * CoalBaron implementation : © Timothée Pecatte <tim.pecatte@gmail.com>, joesimpson <1324811+joesimpson@users.noreply.github.com>
 *
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 *
 * stats.inc.php
 *
 * CoalBaron game statistics description
 *
 */

require_once 'modules/php/constants.inc.php';

$stats_type = [
  'table' => [],

  'value_labels' => [],

  'player' => [ 
    //A score stat to enable comparison with average player's score
    "score" => array("id"=> 10,
      "name" => totranslate("Score"),
      "type" => "int" ),

    "turnOrder1" => array("id"=> 11,
      "name" => totranslate("Shift 1 - Turn order"),
      "type" => "int" ),
    "turnOrder2" => array("id"=> 12,
      "name" => totranslate("Shift 2 - Turn order"),
      "type" => "int" ),
    "turnOrder3" => array("id"=> 13,
      "name" => totranslate("Shift 3 - Turn order"),
      "type" => "int" ),

    "nbActions" => array("id"=> 14,
      "name" => totranslate("Actions done"),
      "type" => "int" ),
    "nbActions1" => array("id"=> 15,
      "name" => totranslate("Minecarts factory actions done"),
      "type" => "int" ),
    "nbActions2" => array("id"=> 16,
      "name" => totranslate("Mining actions done"),
      "type" => "int" ),
    "nbActions3" => array("id"=> 17,
      "name" => totranslate("Delivery actions done"),
      "type" => "int" ),
    "nbActions4" => array("id"=> 18,
      "name" => totranslate("Money actions done"),
      "type" => "int" ),
    "nbActions5" => array("id"=> 19,
      "name" => totranslate("New order actions done"),
      "type" => "int" ),   
    
    "cardsReceived" => array("id"=> 30,
      "name" => totranslate("Cards received"),
      "type" => "int" ),
    "cardsDrawn" => array("id"=> 31,
      "name" => totranslate("Cards taken from the deck"),
      "type" => "int" ),
    "cardsDelivered" => array("id"=> 32,
      "name" => totranslate("Cards delivered"),
      "type" => "int" ),
      
    "moneyReceived" => array("id"=> 33,
      "name" => totranslate("Money received"),
      "type" => "int" ),
    "moneySpent" => array("id"=> 34,
      "name" => totranslate("Money spent"),
      "type" => "int" ),
    "moneyLeft" => array("id"=> 35,
      "name" => totranslate("Money at the end"),
      "type" => "int" ),

    "tilesReceived" => array("id"=> 36,
      "name" => totranslate("Tiles received"),
      "type" => "int" ),
    "tilesDrawn" => array("id"=> 37,
      "name" => totranslate("Tiles taken from the deck"),
      "type" => "int" ),
    "tilesLight" => array("id"=> 38,
      "name" => totranslate("Light tiles"),
      "type" => "int" ),
    "tilesDark" => array("id"=> 39,
      "name" => totranslate("Dark tiles"),
      "type" => "int" ),
      
    "coalsReceived" => array("id"=> 40,
      "name" => totranslate("Coals received"),
      "type" => "int" ),
    YELLOW_COAL."Received" => array("id"=> 41,
      "name" => totranslate("Yellow coals received"),
      "type" => "int" ),
    BROWN_COAL."Received" => array("id"=> 42,
      "name" => totranslate("Brown coals received"),
      "type" => "int" ),
    GREY_COAL."Received" => array("id"=> 43,
      "name" => totranslate("Grey coals received"),
      "type" => "int" ),
    BLACK_COAL."Received" => array("id"=> 44,
      "name" => totranslate("Black coals received"),
      "type" => "int" ),
    "coalsPlacedOnCard" => array("id"=> 45,
      "name" => totranslate("Coals placed on order cards"),
      "type" => "int" ),
    "coalsDelivered" => array("id"=> 46,
      "name" => totranslate("Coals delivered with order cards"),
      "type" => "int" ),
    "coalsLeft" => array("id"=> 47,
      "name" => totranslate("Coals remaining"),
      "type" => "int" ),
      
    "miningMovesReceived" => array("id"=> 50,
      "name" => totranslate("Mining work steps received"),
      "type" => "int" ),
    "miningMovesDone" => array("id"=> 51,
      "name" => totranslate("Mining work steps done"),
      "type" => "int" ),

      
    "scoreMajority1_1" => array("id"=> 61,
      "name" => totranslate("Score for reward #1 - shift #1"),
      "type" => "int" ),
    "scoreMajority1_2" => array("id"=> 62,
      "name" => totranslate("Score for reward #1 - shift #2"),
      "type" => "int" ),
    "scoreMajority1_3" => array("id"=> 63,
      "name" => totranslate("Score for reward #1 - shift #3"),
      "type" => "int" ),
    "scoreMajority2_1" => array("id"=> 64,
      "name" => totranslate("Score for reward #2 - shift #1"),
      "type" => "int" ),
    "scoreMajority2_2" => array("id"=> 65,
      "name" => totranslate("Score for reward #2 - shift #2"),
      "type" => "int" ),
    "scoreMajority2_3" => array("id"=> 66,
      "name" => totranslate("Score for reward #2 - shift #3"),
      "type" => "int" ),
    "scoreMajority3_1" => array("id"=> 67,
      "name" => totranslate("Score for reward #3 - shift #1"),
      "type" => "int" ),
    "scoreMajority3_2" => array("id"=> 68,
      "name" => totranslate("Score for reward #3 - shift #2"),
      "type" => "int" ),
    "scoreMajority3_3" => array("id"=> 69,
      "name" => totranslate("Score for reward #3 - shift #3"),
      "type" => "int" ),
    "scoreMajority4_1" => array("id"=> 70,
      "name" => totranslate("Score for reward #4 - shift #1"),
      "type" => "int" ),
    "scoreMajority4_2" => array("id"=> 71,
      "name" => totranslate("Score for reward #4 - shift #2"),
      "type" => "int" ),
    "scoreMajority4_3" => array("id"=> 72,
      "name" => totranslate("Score for reward #4 - shift #3"),
      "type" => "int" ),
    "scoreMajority5_2" => array("id"=> 73,
      "name" => totranslate("Score for reward #5 - shift #2"),
      "type" => "int" ),
    "scoreMajority5_3" => array("id"=> 74,
      "name" => totranslate("Score for reward #5 - shift #3"),
      "type" => "int" ),
    "scoreMajority6_2" => array("id"=> 75,
      "name" => totranslate("Score for reward #6 - shift #2"),
      "type" => "int" ),
    "scoreMajority6_3" => array("id"=> 76,
      "name" => totranslate("Score for reward #6 - shift #3"),
      "type" => "int" ),
    "scoreMajority7_2" => array("id"=> 77,
      "name" => totranslate("Score for reward #7 - shift #2"),
      "type" => "int" ),
    "scoreMajority7_3" => array("id"=> 78,
      "name" => totranslate("Score for reward #7 - shift #3"),
      "type" => "int" ),
    "scoreMajority8_2" => array("id"=> 79,
      "name" => totranslate("Score for reward #8 - shift #2"),
      "type" => "int" ),
    "scoreMajority8_3" => array("id"=> 80,
      "name" => totranslate("Score for reward #8 - shift #3"),
      "type" => "int" ),
    "scoreMajority9_3" => array("id"=> 81,
      "name" => totranslate("Score for reward #9 - shift #3"),
      "type" => "int" ),
    "scoreMajority10_3" => array("id"=> 82,
      "name" => totranslate("Score for reward #10 - shift #3"),
      "type" => "int" ),
    "scoreMajority11_3" => array("id"=> 83,
      "name" => totranslate("Score for reward #11 - shift #3"),
      "type" => "int" ),
    "scoreMajority12_3" => array("id"=> 84,
      "name" => totranslate("Score for reward #12 - shift #3"),
      "type" => "int" ),
   ],
];
